### ISSUE TITLE
LocalFileSystemProvider.GetSizeOnAllDisks throws "System.IO.IOException: The device is not ready"

### ISSUE THREAD

**Issue by Tirraon** [worldbeater/Camelotia#16]
Stacktrace:

>   at System.IO.DriveInfo.get_AvailableFreeSpace()
   at Camelotia.Services.Providers.LocalFileSystemProvider.<>c.<GetSizeOnAllDisks>b__29_0(DriveInfo x) in C:\Users\maxka\Source\Repos\Camelotia\Camelotia.Services\Providers\LocalFileSystemProvider.cs:line 116
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.Sum(IEnumerable`1 source)
   at Camelotia.Services.Providers.LocalFileSystemProvider.GetSizeOnAllDisks() in C:\Users\maxka\Source\Repos\Camelotia\Camelotia.Services\Providers\LocalFileSystemProvider.cs:line 115
   at Camelotia.Services.Providers.LocalFileSystemProvider.get_Size() in C:\Users\maxka\Source\Repos\Camelotia\Camelotia.Services\Providers\LocalFileSystemProvider.cs:line 14
   at Camelotia.Presentation.ViewModels.ProviderViewModel.get_Size() in C:\Users\maxka\Source\Repos\Camelotia\Camelotia.Presentation\ViewModels\ProviderViewModel.cs:line 281

![image](https://user-images.githubusercontent.com/3163374/53682184-c91ba200-3cfb-11e9-8e99-f50aab0b5a5a.png)

**Comment by Tirraon** [comment]
@worldbeater look like #3 doesn't fix every case.
I have card reader, and in case, when there is no any card in it, DriveInfo.IsReady = false.

**Comment by Tirraon** [comment]
Fixed :shipit:
